{% set name = "napari-console" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ba4f7e1cdca65a7924631372a5e58884e2e35a2b9092c79b98acb9c2dfe1254f


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - setuptools_scm
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - ipykernel >=5.2.0
    - ipython >=7.7.0
    - qtconsole-base >=4.5.1,!=4.7.6,!=5.4.2
    - qtpy >=1.7.0

test:
  requires:
    - pyqt
    - napari >=0.5.0
    - python {{ python_min }}
  imports:
    - napari_console

about:
  home: https://github.com/napari/napari-console
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A plugin that adds a console to napari
  description: |
    napari-console is a plugin for the napari n-dimensional image
    viewer. It adds an IPython console to the viewer, allowing users
    to interact with the viewer's API.
  doc_url: https://github.com/napari/napari-console
  dev_url: https://github.com/napari/napari-console

extra:
  recipe-maintainers:
    - sofroniewn
    - jni
    - tlambert03
