{% set name = "napari-console" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bc86dd96cf94b1af96bba1043f90a39b1369bb978a8df9038a1ac422e66b532


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - setuptools_scm
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - ipykernel >=5.2.0
    - ipython >=7.7.0
    - napari-plugin-engine >=0.1.9
    - qtconsole-base >=4.5.1,!=4.7.6,!=5.4.2
    - qtpy >=1.7.0

test:
  requires:
    - pyqt
  imports:
    - napari_console

about:
  home: https://github.com/napari/napari-console
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A plugin that adds a console to napari
  description: |
    napari-console is a plugin for the napari n-dimensional image
    viewer. It adds an IPython console to the viewer, allowing users
    to interact with the viewer's API.
  doc_url: https://github.com/napari/napari-console
  dev_url: https://github.com/napari/napari-console

extra:
  recipe-maintainers:
    - sofroniewn
    - jni
    - tlambert03
